### ISSUE TITLE
关于数据增强

### ISSUE THREAD

**Issue by TVayne** [Solemoon/XMorpher#1]
您好。
我看您提供代码里面包括数据增强，请问论文中的结果（包括其他方法）有使用数据增强吗？

**Comment by Solemoon** [comment]
你好，是使用的！所有的对比实验的数据预处理、训练框架等变量均严格控制为相同，从而确保性能的提升是由我们提出的XMorpher网络带来的。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Solemoon/XMorpher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月4日(星期二) 下午4:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Solemoon/XMorpher] 关于数据增强 (Issue #1)





 
您好。
 我看您提供代码里面函数增强，请问论文中的结果（包括其他方法）有使用数据增强吗？
